<center><u><H1>NUMPY</H1><u></center>   

In [1]:
import numpy as np

<b>Creating an array:</b>

In [2]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
ones = np.ones((2,3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [4]:
rand = np.random.random((2,3))
rand

array([[0.65479526, 0.88081497, 0.46207094],
       [0.846202  , 0.62086424, 0.87592656]])

In [5]:
mu, sigma = 2, 0.5
v = np.random.normal(mu,sigma,100)
v

array([1.45832907, 1.96881342, 2.07946653, 1.28267483, 1.43735137,
       2.90063299, 2.90869119, 1.94982098, 2.31552066, 1.87358644,
       2.63659851, 2.04168506, 1.60822313, 2.66784055, 2.13264505,
       2.1132349 , 2.11036801, 1.51061126, 2.91944771, 1.74311302,
       2.74762892, 2.42057529, 2.19753742, 2.33808827, 2.29136947,
       2.22318055, 2.89175432, 1.8210939 , 2.34498078, 2.36907633,
       1.29790569, 0.50513567, 2.48465202, 1.97530769, 2.08414939,
       1.95631833, 1.77205112, 1.43899945, 2.03726393, 2.05571508,
       1.59125973, 2.15434328, 1.37137122, 2.06848357, 3.11476496,
       1.75641741, 1.6775914 , 1.99472698, 1.80983039, 1.82227326,
       1.02933598, 2.92743748, 1.54236212, 2.89061032, 1.60040287,
       2.56754616, 1.73604045, 1.32946684, 1.33460451, 2.59070649,
       2.38051161, 2.13412589, 2.02479106, 1.55849322, 1.73019276,
       1.32132873, 2.36090032, 1.27975745, 0.89030456, 2.06205294,
       1.5721828 , 1.93575115, 2.51355199, 2.63352686, 1.84605

<b>Check the attributes:</b>

In [6]:
arr.ndim

2

In [7]:
arr.shape

(3, 3)

In [8]:
arr.size

9

In [9]:
arr.dtype.name

'int32'

<H3>Mathematical Operations:</H3>

In [10]:
#Substraction
a = np.array([6,5,4,8])
b = np.array([1,2,5,10])
a-b

array([ 5,  3, -1, -2])

In [11]:
#Squaring an array
b**2

array([  1,   4,  25, 100], dtype=int32)

In [12]:
#Applying trigonometic functions
np.sin(b)

array([ 0.84147098,  0.90929743, -0.95892427, -0.54402111])

In [13]:
#Conditional operations
b>1

array([False,  True,  True,  True])

In [14]:
#Unique values
values = [5,2,1,1,6,2,0,1]
np.unique(values)

array([0, 1, 2, 5, 6])

In [15]:
arr.sum(axis=0) 

array([ 9, 12, 15])

In [16]:
arr.sum(axis=1) 

array([ 3, 12, 21])

In [17]:
arr.min(axis=1)

array([0, 3, 6])

In [18]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [19]:
# floor: returns the floor of each element
np.floor([0.5,1.1,-1.2,5,-2.0])

array([ 0.,  1., -2.,  5., -2.])

<h3>Indexing and slicing:</h3>

In [20]:
#Index positions
a = np.array([[3,4,5],[7,8,3],[0,3,23],[8,11,6]])
a.shape

(4, 3)

In [21]:
a[1,1]

8

In [22]:
a[0,0:2]

array([3, 4])

In [23]:
a[0,:]

array([3, 4, 5])

In [24]:
a[:,1]

array([ 4,  8,  3, 11])

In [25]:
a[:,-1]

array([ 5,  3, 23,  6])

### Iterating:

In [26]:
print(np.arange(5))

[0 1 2 3 4]


In [27]:
c = np.linspace(-2,2,20)
c

array([-2.        , -1.78947368, -1.57894737, -1.36842105, -1.15789474,
       -0.94736842, -0.73684211, -0.52631579, -0.31578947, -0.10526316,
        0.10526316,  0.31578947,  0.52631579,  0.73684211,  0.94736842,
        1.15789474,  1.36842105,  1.57894737,  1.78947368,  2.        ])

In [28]:
#The enumerate() function adds a counter to an iterable
y = [1, 1, 2, 2, 1, 1,3]
for index, item in enumerate(np.unique(y)):
    print(index, item+1)

0 2
1 3
2 4


In [29]:
for index, item in enumerate(np.arange(len(y))):
    print(index, item+1)

0 1
1 2
2 3
3 4
4 5
5 6
6 7


### Shape Manipulation:

In [30]:
# returns the array, flattened
a.ravel()

array([ 3,  4,  5,  7,  8,  3,  0,  3, 23,  8, 11,  6])

In [31]:
a.shape=(6,2)
a

array([[ 3,  4],
       [ 5,  7],
       [ 8,  3],
       [ 0,  3],
       [23,  8],
       [11,  6]])

In [32]:
a.transpose()

array([[ 3,  5,  8,  0, 23, 11],
       [ 4,  7,  3,  3,  8,  6]])

In [33]:
a.T.shape

(2, 6)

In [34]:
a.reshape(4,3)

array([[ 3,  4,  5],
       [ 7,  8,  3],
       [ 0,  3, 23],
       [ 8, 11,  6]])

In [35]:
# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated
a.reshape(3,-1)

array([[ 3,  4,  5,  7],
       [ 8,  3,  0,  3],
       [23,  8, 11,  6]])

In [36]:
# The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:
b = np.array([[ 0.2,  18.,  20.,  4.],
       [ 41.,  15.,  11.,  10.],
       [ 0.5,  19.,  13.,  0.6]])
b.resize((2,6))

In [37]:
b

array([[ 0.2, 18. , 20. ,  4. , 41. , 15. ],
       [11. , 10. ,  0.5, 19. , 13. ,  0.6]])

In [38]:
#Floor: Return the floor of the input, element-wise
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [39]:
# NEW AXIS
x1 = np.array([1, 2, 3, 4, 5])
x1_new = x1[:, np.newaxis]
x1_new

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [40]:
x2 = np.array([5, 4, 3])
x3 = x1_new + x2
x3

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

In [41]:
x3_new = x3[:,np.newaxis,1]
x3_new

array([[5],
       [6],
       [7],
       [8],
       [9]])

## Stacking different arrays

In [42]:
c = np.floor(10*np.random.random((2,2)))
c

array([[0., 9.],
       [9., 3.]])

In [43]:
d = np.floor(10*np.random.random((2,2)))
d

array([[0., 3.],
       [6., 2.]])

In [44]:
# vstack: vertical aggregation
np.vstack((c,d))

array([[0., 9.],
       [9., 3.],
       [0., 3.],
       [6., 2.]])

In [45]:
# hstack: horizontal aggregation
np.hstack((c,d))

array([[0., 9., 0., 3.],
       [9., 3., 6., 2.]])

## Splitting arrays

In [46]:
hs = np.floor(10*np.random.random((2,12))) 
hs

array([[9., 4., 7., 1., 2., 8., 3., 3., 5., 0., 6., 7.],
       [0., 2., 2., 5., 3., 6., 3., 7., 4., 6., 4., 1.]])

In [47]:
# Split a into 3
hsp = np.hsplit(hs,3)
hsp

[array([[9., 4., 7., 1.],
        [0., 2., 2., 5.]]), array([[2., 8., 3., 3.],
        [3., 6., 3., 7.]]), array([[5., 0., 6., 7.],
        [4., 6., 4., 1.]])]

In [48]:
hsp[2]

array([[5., 0., 6., 7.],
       [4., 6., 4., 1.]])

## Linear Algebra:

In [49]:
la = np.array([[1.0, 2.0], [3.0, 4.0]])
print(la)

[[1. 2.]
 [3. 4.]]


In [50]:
la.transpose()

array([[1., 3.],
       [2., 4.]])

In [51]:
np.linalg.inv(la)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [52]:
# unit 2x2 matrix; "eye" represents "I"
I = np.eye(2) 
I

array([[1., 0.],
       [0., 1.]])

In [53]:
#Matrix multiplication
M1 = np.array([[1,2],[0,1]])
M2 = np.array([[-1,0],[1,1]])
M1*M2

array([[-1,  0],
       [ 0,  1]])

In [54]:
#The dot product
np.dot(M1,M2)

array([[1, 2],
       [1, 1]])

In [55]:
# trace
np.trace(I)  

2.0

In [56]:
#Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8
c0 = np.array([[3,1], [1,2]])
c1 = np.array([9,8])
solve = np.linalg.solve(c0, c1)
solve

array([2., 3.])

In [57]:
#Eigenvalues and eigenvectors
#Eigenvalues are scalar solutions ot the equation Ax = ax, where A is a 2D matrix
#and x is a 1-D vector. Eigenvectors are vectors corresponding to eigenvalues.
A = np.mat("3 -2; 1 0")
A

matrix([[ 3, -2],
        [ 1,  0]])

In [58]:
print("Eigenvalues:\n", np.linalg.eigvals(A))

Eigenvalues:
 [2. 1.]


In [59]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [2. 1.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [60]:
#Singular Value decomposition
B = np.mat("4 11 14; 8 7 -2")
B

matrix([[ 4, 11, 14],
        [ 8,  7, -2]])

In [61]:
#Singular Value Decomposition:
# is a type of factorization that decomposes a matrix into a product of 3 matrices.
U, Sigma, V = np.linalg.svd(B, full_matrices=False) # reduced SVD
#full_matrices : bool, optional
#If True (default), u and v have the shapes (M, M) and (N, N), respectively.
#Otherwise, the shapes are (M, K) and (K, N), respectively, where K = min(M, N).

In [62]:
print("U:\n", U)
print("Sigma:\n", Sigma)
print("V:\n", V)

U:
 [[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]
Sigma:
 [18.97366596  9.48683298]
V:
 [[-0.33333333 -0.66666667 -0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]


In [63]:
print("Product:\n", U * np.diag(Sigma) * V)

Product:
 [[ 4. 11. 14.]
 [ 8.  7. -2.]]


## Reference:

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html