# Numpy Tutorial I

NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers. In some ways,
NumPy arrays are like Python’s built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size.
This notebook will deal with:
(i) Basics of Numpy Arrays.
(ii) Computation on Numpy Arrays

In [1]:
# Check the version of numpy
import numpy as np
np.__version__ #Double underscore

'1.16.4'

### Creating Arrays from Python lists  

In [2]:
# integer array
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
# Unlike Python lists, NumPy is constrained to arrays that all contain the same type. 
# If types do not match, NumPy will upcast if possible (here, integers are upcast to floating point):
np.array([3.14, 1, 2, 3])

array([3.14, 1.  , 2.  , 3.  ])

In [4]:
# If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
# Unlike Python lists, NumPy arrays can explicitly be multidimensional
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating arrays from scratch 

In [6]:
# Create a length-10 array filled with zeros (by default it will be float type)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[0.3659733 , 0.21639663, 0.19497844],
       [0.67628778, 0.30754685, 0.53234254],
       [0.42481306, 0.75034511, 0.79939119]])

In [13]:
# Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3,3))

array([[ 0.335001  ,  0.86538414, -0.44267237],
       [-0.44057091, -0.28848829, -2.110381  ],
       [ 0.37759172,  1.12571613,  0.24107661]])

In [14]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3,3))

array([[8, 4, 4],
       [1, 0, 7],
       [2, 2, 9]])

In [15]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

### Numpy Array Attributes 

In [17]:
# We’ll use NumPy’s random number generator, which we will seed with a set value in order to
# ensure that the same random arrays are generated each time this code is run:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size = 6) # one dimensional array
x2 = np.random.randint(10, size = (3,4)) # two dimensional array
x3 = np.random.randint(10, size = (3, 4, 5)) # three dimensional array

In [18]:
#Each array has attributes ndim (the number of dimensions), shape (the size of each #dimension), 
# and size (the total size of the array):
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [19]:
# dtype
print("dtype: ", x3.dtype)

dtype:  int32


In [20]:
# itemsize: lists the size (in bytes) of each array element.
# nbytes: lists the total size (in bytes) of the array.
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

itemsize:  4 bytes
nbytes:  240 bytes


### Array Indexing 

In [21]:
x1

array([5, 0, 3, 3, 7, 9])

In [22]:
x1[0] # indexing first element of the array

5

In [23]:
x1[-1] # indexing last element of the array

9

In [24]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [25]:
x2[0,0] # indexing first element of the array

3

In [26]:
x2[2,0]

1

In [27]:
x2[2,-1]

7

In [28]:
# Modifying the elements
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [29]:
# Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
# This means, for example, that if we attempt to insert a floating-point value to an integer array, the
# value will be silently truncated.
# For example:
x1[0] = 3.145
x1

array([3, 0, 3, 3, 7, 9])

### Array slicing 

In [30]:
# The NumPy slicing syntax follows that of the standard Python list. 
# To access a slice of an array x, use this: x[start:stop:step]
# If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1.
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[:5] # first 5 elements

array([0, 1, 2, 3, 4])

In [32]:
x[5:] # elements after 5th index

array([5, 6, 7, 8, 9])

In [33]:
x[4:7]

array([4, 5, 6])

In [34]:
x[::2] # slicing array with a step size of 2

array([0, 2, 4, 6, 8])

In [35]:
x[1::2] # slicing array with a step size of 2, beginning at x[1]

array([1, 3, 5, 7, 9])

In [36]:
# When the step value is negative: In this case, the defaults for start and stop are swapped
x[::-1] # All values are reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [37]:
x[5::-2] # reversed every other from 5th index 

array([5, 3, 1])

In [38]:
# Multidimensional slices work in the same way, with multiple slices separated by commas.
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [39]:
x2[:2, :3] # two rows and three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [40]:
x2[:3, ::2] # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [41]:
# subarray dimensions can even be reversed together
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [42]:
# Accessing rows and columns
print(x2[:,0]) # all rows and first column

[12  7  1]


In [43]:
print(x2[0,:]) # first row and all columns

[12  5  2  4]


In [44]:
# In the case of row access, the empty slice can be omitted for a more compact syntax:
print(x2[0])

[12  5  2  4]


In [45]:
#One important—and extremely useful—thing to know about array slices is that they
#return views rather than copies of the array data. This is one area in which NumPy
#array slicing differs from Python list slicing: in lists, slices will be copies
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [46]:
# Sub-array extracted from x2
x2_sub = x2[:2,:2]
x2_sub

array([[12,  5],
       [ 7,  6]])

In [47]:
# Now if we modify this subarray, we’ll see that the original array is changed!
x2_sub[0,0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [48]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [49]:
# Creating copies of arrays
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [50]:
x2_sub_copy[0,0] = 42
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

In [51]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### Array reshaping 

In [52]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
# Another common reshaping pattern is the conversion of a one-dimensional array
# into a two-dimensional row or column matrix. We can do this with the reshape
# method, or more easily by making use of the newaxis keyword within a slice operation.
x = np.array([1,2,3])
#row vector via reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [54]:
# row vector via newaxis
x[np.newaxis,:]

array([[1, 2, 3]])

In [55]:
# column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [56]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

### Concatenation of arrays 

In [57]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [59]:
# We can concatenate more than two arrays at once
z = [99, 99, 99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [60]:
# Concatenation of multi-dimensional arrays
np.concatenate([grid,grid]) # Concatenate along the first axis

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
# Concatenate along the second axis
np.concatenate([grid,grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [62]:
x

array([1, 2, 3])

In [63]:
# Verically stack the arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
np.vstack([grid,x])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [65]:
# Horizontally stack the arrays
np.hstack([x,grid]) # Input arrays must have same dimensions. So this statement will give an error.

ValueError: all the input arrays must have same number of dimensions

In [66]:
xnew = x.reshape(-1,1)
xnew

array([[1],
       [2],
       [3]])

In [67]:
np.hstack([xnew, grid])

array([[1, 1, 2, 3],
       [2, 4, 5, 6],
       [3, 7, 8, 9]])

### Splitting of arrays 

In [68]:
# The opposite of concatenation is splitting, which is implemented by the functions
# np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points
# N split points lead to N + 1 subarrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [69]:
grid2 = np.arange(16).reshape((4, 4))
grid2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
upper, lower = np.vsplit(grid2, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [71]:
left, right = np.hsplit(grid2, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
